authors: []
blacklist: []
build_space: build_pal_deploy
catkin_make_args: []
cmake_args:
- -DCATKIN_BUILD_BINARY_PACKAGE=0
- -DCMAKE_CXX_FLAGS_DEBUG=-g -O0 -UNDEBUG
- -DCMAKE_C_FLAGS_DEBUG=-g -O0
- -UNDEBUG
- -DCMAKE_CXX_FLAGS_DEPLOY:String=-g -O2 -fdebug-prefix-map=/home/pal/ctrl2_ws=. -fstack-protector-strong
  -Wformat -Werror=format-security
- -DCMAKE_BUILD_TYPE=Deploy
- -DCATKIN_ENABLE_TESTING=OFF
devel_layout: linked
devel_space: devel_pal_deploy
extend_path: null
extends: null
install: true
install_space: /home/pal/ctrl2_ws/install_pal_deploy/home/pal/deployed_ws
isolate_install: false
jobs_args: []
licenses:
- TODO
log_space: logs_pal_deploy
maintainers: []
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
