// Generated by gencpp from file my_controller_pkg/THK_AMS_msg1.msg
// DO NOT EDIT!


#ifndef MY_CONTROLLER_PKG_MESSAGE_THK_AMS_MSG1_H
#define MY_CONTROLLER_PKG_MESSAGE_THK_AMS_MSG1_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_controller_pkg
{
template <class ContainerAllocator>
struct THK_AMS_msg1_
{
  typedef THK_AMS_msg1_<ContainerAllocator> Type;

  THK_AMS_msg1_()
    : x(0.0)
    , y(0.0)
    , angle(0.0)  {
    }
  THK_AMS_msg1_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator> const> ConstPtr;

}; // struct THK_AMS_msg1_

typedef ::my_controller_pkg::THK_AMS_msg1_<std::allocator<void> > THK_AMS_msg1;

typedef boost::shared_ptr< ::my_controller_pkg::THK_AMS_msg1 > THK_AMS_msg1Ptr;
typedef boost::shared_ptr< ::my_controller_pkg::THK_AMS_msg1 const> THK_AMS_msg1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator1> & lhs, const ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator1> & lhs, const ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_controller_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57832a67d2f8a00310788a06c92c59b2";
  }

  static const char* value(const ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57832a67d2f8a003ULL;
  static const uint64_t static_value2 = 0x10788a06c92c59b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_controller_pkg/THK_AMS_msg1";
  }

  static const char* value(const ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Coordinates\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 angle\n"
"\n"
;
  }

  static const char* value(const ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct THK_AMS_msg1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_controller_pkg::THK_AMS_msg1_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CONTROLLER_PKG_MESSAGE_THK_AMS_MSG1_H
